### ISSUE TITLE
Bevy Integration

### ISSUE THREAD

**Issue by fxtressia** [Inochi2D/inox2d#1]
We will need to have our code compatible with Bevy's ECS API. Then we can easily implement it in a separate crate.

# Implementation Overview
Bevy uses an [Entity Component System (ECS)](https://bevy-cheatbook.github.io/programming/ecs-intro.html) system. 

For its windowing events, Bevy doesn't pass the events from Winit, but send its own event data listed in [`bevy::window`](https://docs.rs/bevy/latest/bevy/window/index.html) using Bevy ECS.

For the rendering part, bevy provides an API trough the [Renderer Sub-App](https://bevy-cheatbook.github.io/gpu.html).

**Comment by Speykious** [comment]
We should probably focus on making the WGPU renderer first (#2), since that was planned from the start.

**Comment by fxtressia** [comment]
> We should probably focus on making the WGPU renderer first (#2), since that was planned from the start.

Yup! But let's write it with Bevy ECS in mind, so we don't have to rewrite things.

**Comment by Speykious** [comment]
Since a few days ago I removed the WGPU renderer due to not being able to maintain it as of now, I think it's best to close this issue as not planned. I'm going to start worrying about bevy integration further into the future, when I get to properly learn WGPU and after having prioritized making sure it works in browsers with WASM.

**Comment by fxtressia** [comment]
Alright. I hope we can one day reopen this issue some day in the future.

**Comment by TheKnarf** [comment]
I keep checking in on inox2d like once or twice a year to see if I can use it with Bevy yet, it seems I keep being disappointed.

**Comment by Speykious** [comment]
Sorry about that. I have been completely inactive on this project for a long time now. I'm really not the best dev when it comes to being disciplined and keeping projects alive :/

**Comment by TheKnarf** [comment]
> Sorry about that. I have been completely inactive on this project for a long time now. I'm really not the best dev when it comes to being disciplined and keeping projects alive :/

No worries, I'm the exact same 😅 But perhaps we could re-open this issue and take a new look at getting WGPU inn? I know there was a PR a while back to get it back inn?

**Comment by Speykious** [comment]
But getting it in means maintaining it. What good is reopening this issue if I'm not capable of doing that?
I think you'd have more chances with a fork unfortunately.
