### ISSUE TITLE
Wgpu renderer

### ISSUE THREAD

**Issue by fxtressia** [Inochi2D/inox2d#2]
This would make Bevy integration easier ^^

**Comment by ghost** [comment]
Hmmm, how can i help?

**Comment by Speykious** [comment]
> Hmmm, how can i help?

Are you in the [Inochi2D discord server](https://discord.com/invite/abnxwN6r9v)?

**Comment by ghost** [comment]
Yes!!

**Comment by fxtressia** [comment]
Closed as #26 has been merged.
