### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fxtressia** [Inochi2D/inox2d#8]
@Speykious what do you think about switching to `MIT OR APACHE-2.0`? It would make Inox integrates better with the rest of the Rust ecosystem. (or we could even move to `MIT OR APACHE-2.0 OR BSD-2-Clause` but won't that make everyone vomit?)

**Comment by Speykious** [comment]
Not really sure. I think I care more about having a license that is roughly the same as Inochi2D rather than fitting with the rest of the Rust ecosystem.

At first I wanted BSC 3-Clause but I figured I'll just choose Inochi2D's license for now.

**Comment by LunaTheFoxgirl** [comment]
@fianathedevgirl BSD 2-clause is the most game development friendly license, MIT has a weird sublicensing clause that makes in unattractive and Apache 2 likewise has a lot of legalese that makes it unattractive.
