### ISSUE TITLE
Doesn't seem to work with example models

### ISSUE THREAD

**Issue by TheKnarf** [Inochi2D/inox2d#80]
I downloaded the example models from https://lunafoxgirlvt.itch.io/inochi-creator and tried running them with the `examples/render-wgpu` project inside `inox2d` and it didn't work.

I realise that the Rust implementation might not be up to par yet, but is there an example model out there that does work with the currently implemented feature set in the Rust version? I'd like to try and use inox2d with wgpu and Rust in a project I'm working on and would love to see an example that works.

```
cargo run -- ~/Downloads/example-models/Midori.inx
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `/Users/knarf/projects/inox2d/target/debug/render-wgpu /Users/knarf/Downloads/example-models/Midori.inx`
thread 'Image Decoder Thread (7)' panicked at inox2d/src/texture/tga.rs:294:50:
range end index 430336 out of range for slice of length 384416
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Image Decoder Thread (8)' panicked at inox2d/src/texture/tga.rs:294:50:
thread 'thread 'Image Decoder Thread (4)Image Decoder Thread (2)' panicked at ' panicked at inox2d/src/texture/tga.rs:348:9:
index out of bounds: the len is 1328 but the index is 1328
thread 'range end index 19873764 out of range for slice of length 5322852Image Decoder Thread (9)' panicked at inox2d/src/texture/tga.rs
inox2d/src/texture/tga.rs:294:50:
range end index 643204 out of range for slice of length 524508
:294:50:
range end index 1988100 out of range for slice of length 1793520
thread 'Image Decoder Thread (6)' panicked at inox2d/src/texture/tga.rs:294:50:
range end index 18783556 out of range for slice of length 6683028
thread 'Image Decoder Thread (3)' panicked at inox2d/src/texture/tga.rs:348:9:
index out of bounds: the len is 4032 but the index is 4032
thread 'Image Decoder Thread (5)' panicked at inox2d/src/texture/tga.rs:294:50:
range end index 3027600 out of range for slice of length 2408160
thread 'Image Decoder Thread (1)' panicked at inox2d/src/texture/tga.rs:348:9:
index out of bounds: the len is 2568 but the index is 2568
thread 'Image Decoder Thread (0)' panicked at inox2d/src/texture/tga.rs:348:9:
index out of bounds: the len is 4028 but the index is 4028
^C
```

**Comment by TheKnarf** [comment]
Just checked the readme and saw this:

> INP parsing works completely fine, but not INX (bad indexes, wrong reading?).

Did not realize that there where different formats and only one of them currently work with `inox2d`. Where can I download a test model in the INP format?

**Comment by Speykious** [comment]
You can export a `.inp` from your `.inx` using Inochi Creator

**Comment by Speykious** [comment]
![image](https://github.com/Inochi2D/inox2d/assets/13885008/c42f6896-35e5-40df-b931-e28d580acc6f)

**Comment by Speykious** [comment]
I guess I could put a message about `.inx` in the examples instead of trying to read it :v

**Comment by Speykious** [comment]
I feel quite ashamed for not fixing this bug sooner, but it looks like I didn't need to put a message about the `.inx` format not working, thanks to #82 merged in.
It works now!

**Comment by TheKnarf** [comment]
Great! Now it works out of the box without converting the model.
